name: deep_vocab
description: Deep Vocab

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0 # provider
  auto_size_text: ^3.0.0-nullsafety.0 # text
  badges: ^2.0.1 # badge
  bottom_navigation_badge:
    path: submodule/bottom_navigation_badge
  intl: ^0.17.0
  dio: ^4.0.0 # for http, depends on http
  http: ^0.13.3
  cached_network_image: ^3.0.0
  uuid: ^3.0.4 # for uuid
  graphql: ^5.0.0 # for http
  flutter_screenutil: ^5.0.0+2 # for resizing screen
  hive: ^2.0.4 # for hive database
  hive_flutter: ^1.0.0 # for hive database
  path_provider: ^2.0.2 # for RESTFUL download
  crypto: ^3.0.1 # for encryption
  pull_to_refresh: ^2.0.0 # for slider refresh
  google_nav_bar: ^5.0.5 # for top tab bar
#  fsearch: ^1.0.1 # for search bar
  sliding_up_panel: ^2.0.0+1 # for sliding up panel
  moor: ^4.3.2 # for sqlite database
  sqlite3_flutter_libs: ^0.5.0 # for sqlite database
  # Version 4.0.1 does not include Null Safety, don't use version above 4.0
  # Version ^4.0.1 for `json_annotation` and ^4.1.0 for `json_serializable recommended
  # See: https://stackoverflow.com/questions/66477445/generator-cannot-target-libraries-that-have-not-been-migrated-to-null-safety
  json_annotation: ^4.0.1 # for sqlite database and json serialization.
  fl_chart: ^0.36.2 # for charts graphing
  f_logs: ^2.0.0 # for print and save log
  package_info_plus: ^1.0.6 # for getting app version and build version
  pin_code_fields: ^7.3.0 # for login and email verification

  # See IOS setup guide: https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md
  # See Android setup guide: https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md
  background_fetch: ^1.0.0 # for background tasks and syncing

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0 # for hive database code generation
  moor_generator: ^4.3.1 # for moor database code generation
  json_serializable: ^4.1.3 # for json code generation
  flutter_launcher_icons: "^0.9.1" # for app icon

# for app icon, provided by [flutter_launcher_icons] package
flutter_icons:
  image_path: "assets/images/icon-353x353.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/icon-512x512-foreground.png"
  adaptive_icon_background: "#06456b"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/config.yaml
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
